spring:
  datasource:
    url: jdbc:mysql://localhost/purchase?createDatabaseIfNotExist=true&useSSL=false
    username: root
  #    password:
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8060
