spring:
  datasource:
    url: jdbc:mysql://localhost/buyer?createDatabaseIfNotExist=true&useSSL=false
    username: root
#    password:
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8070
