server:
  port: 0


spring:
  application:
    name: authors
  datasource:
    url: jdbc:mysql://localhost/author?createDatabaseIfNotExist=true&useSSL=false
    username: root
#    password:
  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: "*"
